### ISSUE TITLE
ASUS Zenbook UX330U Notebook PC

### ISSUE THREAD

**Issue by shawn1thompson** [cassidyjames/oem-info#18]
What should I send to add my laptop (assuming that's something you want here)?

**Comment by Riyadulmollick** [comment]
Hey @shawn1thompson,
You just need to give this data.
- **Manufacturer Name**
- **Product Name**
- **Version Name/Number**
- **A Picture that will work as a logo** ([see this for image requirement](https://github.com/cassidyjames/oem-info#images)) 
- **Support URL**

You can see anyone's work as a reference, it is not so much difficult.

**Comment by shawn1thompson** [comment]
Thanks. Here you are:

- ASUS
- Zenbook
- UX330U Notebook PC
- [Image](https://monaliza.com.my/wp-content/uploads/2019/12/4-6.png)
- [Support](https://www.asus.com/US/supportonly/UX330UA/HelpDesk/)
